apiVersion: v1
kind: Service
metadata:
  name: salam-service
spec:
  type: NodePort
  selector:
    app: salam-queue
  ports:
    - protocol: TCP
      port: 80            # Port exposed on the Service
      targetPort: 3000    # Port the container listens on
      nodePort: 30080     # Fixed external port (optional, range: 30000-32767)

